config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events do
    # with_options(constarints: { format: :json }, on: :collection) do
    get 'get_same', on: :collection
    # end
  end

  get 'home/index'
  root 'home#index'
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  validates_presence_of :title, :start

  belongs_to :user

  # virtual attributes
  attr_accessor :is_requested_apply_for_all_one_based
  attr_accessor :is_requested_delete_one_based
  attr_accessor :end_date_of_series
  attr_accessor :needed_recompute_end_date

  # callbacks
  before_save :update_one_based_records, on: :update, if: :is_requested_apply_for_all_one_based
  after_destroy :delete_one_based_records, if: :is_requested_apply_for_all_one_based
  after_commit :generate_serial_records, on: :create, if: :end_date_of_series
  before_validation :recompute_end_date_by_start_delta, if: :needed_recompute_end_date

  after_validation :ensure_end_date_greater_than_start

  # repeat_interval
  enum repeat_interval: {
    daily: 'd',
    weekly: 'w',
    monthly: 'm',
    yearly: 'y'
  }

  # scopes
  scope :with_same_base, -> (base) { where("base_id = :item_id OR base_id IS NOT NULL AND base_id = :base_id OR id = :base_id", item_id: base.id, base_id: base.base_id) }
  scope :with_same_base_except_self, -> (base) { with_same_base(base).where.not(id: base.id) }

  def generate_serial_records
    return if !repeat_interval || base_id.present? || !end_date_of_series
    case
    when daily?
      generate_records_until(self, end_date_of_series, :day)
    when weekly?
      generate_records_until(self, end_date_of_series, :week)
    when monthly?
      generate_records_until(self, end_date_of_series, :month)
    else
      generate_records_until(self, end_date_of_series, :year)
    end
  end

  private

  def recompute_end_date_by_start_delta
    puts "DEALING"
    if self.start_changed?
      self.end_date = self.end_date + (self.start - self.start_was)
    end
  end

  def ensure_end_date_greater_than_start
    if !end_date.present? || end_date < start
      self.end_date = start.end_of_day
    end
  end

  def generate_records_until(base, end_date_of_series, incr_period)
    current_start_date = base.start + get_next_period(incr_period)
    current_end_date = base.end_date + get_next_period(incr_period)

    while current_end_date < end_date_of_series
      Event.create(attributes.with_indifferent_access.except(:id).merge(start: current_start_date, base_id: id, end_date: current_end_date))
      current_start_date = current_start_date + get_next_period(incr_period)
      current_end_date = current_end_date + get_next_period(incr_period)
    end
  end

  def delete_one_based_records
    Event.with_same_base(self).destroy_all
  end

  def update_one_based_records
    one_based_events = Event.with_same_base_except_self(self)

    one_based_events.each do |evt|
      evt.start = recompute_start(evt, self.start_was, self.start) if self.start_changed?

      if self.end_date_changed?
        evt.end_date = recompute_end(evt, self.end_date_was, self.end_date)
      elsif evt.start_changed? && !self.end_date_changed?
        evt.end_date = evt.end_date + (self.start - self.start_was)
      end
      evt.update(self.attributes.with_indifferent_access.except(:id, :start, :end_date, :base_id))
    end
  end

  def recompute_start(target, source_start_was, curr_source_start)
    target.start + (curr_source_start - source_start_was)
  end

  def recompute_end(target, source_end_was, curr_source_end)
    target.end_date + (curr_source_end - source_end_was)
  end

  def get_next_period(period)
    case period
    when :day then 1.day
    when :week then 1.week
    when :month then 1.month
    else 1.year
    end
  end

  def get_one_based_records
    Event.with_same_base(self).where.not(id: self.id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :get_same]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
    if params[:start] && params[:end]
      @events = @events.where("start >= :start AND end_date <= :end", start: params[:start], end: params[:end])
    end
    respond_with @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_with(@event)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge(user: current_user))
    @event.end_date_of_series = params[:series_end] if params[:series_end]
    @event.save
    respond_with(@event)
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.is_requested_apply_for_all_one_based = true if params[:update_same] && ['t', 'true'].include?(params[:update_same])
    @event.needed_recompute_end_date = true if params[:recompute] && ['t', 'true'].include?(params[:recompute])

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Событие было успешно обновлено.' }
        format.json { render json: @event, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: { errors: @event.errors }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.is_requested_apply_for_all_one_based = true if params[:delete_same] && ['t', 'true'].include?(params[:delete_same])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Событие удалено.' }
      format.json { head :no_content }
    end
  end

  def get_same
    @same_events = Event.with_same_base(@event)
    render json: @same_events
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start, :end_date, :is_repeated, :repeat_interval)
    end
end

app/views/events/_form.html.erb
<div id="evForm" class="event-form" role="dialog">
  <form role="form" id="newEventForm">
    <div class="form-group">              
      <div class="new-event-title">
        <label for="title">Название</label>
        <input type="text" class="form-control" id="title">
      </div>
      <div class="title_errors field_error"></div>
    </div>

    <div class="form-group">
      <div class="new-event-start_date">
        <label for="startDate">Дата</label>
        <input type="text" id="startDate" class="form-control">
      </div>
      <div class="start_date_errors field_error"></div>
    </div>

    <div class="form-group" id="startTime">
      <div class="start_time_errors"></div>
      <div class="new-event-start_date">
        <label for="startTime">Время</label>
        <input type="text" class="form-control" id="startTime">
      </div>
    </div>

    <div class="checkbox">
      <label>
        <input type="checkbox" value="" checked id="isPeriodic">
        Повторяющаяся?
      <label>
    </div>

    <div class="form-group end-date-group" style="display: block">
      <div class="row">
        <div class="col-sm-4">
          <div class="new-event-end_date">
            <label for="endDate">Дата окончания cерии</label>
            <input type="text" class="form-control" id="endDate">
          </div>
        </div>
        <div class="col-sm-4 col-sm-offset-2">
          <div class="repeat_interval_errors"></div>
          <div class="new-event-repeat_interval">
            <%= label_tag 'repeatInterval', 'Интервал повтора' %>
            <%= select_tag 'repeatInterval', options_for_select(Event.repeat_intervals.to_a), prompt: 'Выберите интервал', class: "form-control" %>
          </div>
        </div> 
      </div>  
    </div>   

    <div class="start_date_errors"></div>
    <div class="actions">
      <button id="cnaheTimeBtn" class="pull-left btn btn-default action-btn">Установить время</button>
      <input class="btn btn-success action-btn" id="saveEvent" type="submit" value="Сохранить">
      <button type="button" class="btn btn-default action-btn" data-dismiss="modal">Закрыть</button>
    </div>
  </form>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="userCalendar"></div>

<div id="popupEvent" class="new-event modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 id="popupEventHeader">New event</h3>
      </div>
      <div class="modal-title"></div>
      <form role="form" id="eventForm" class="event-form">
        <div class="modal-body">
          <div class="form-group">              
            <div class="new-event-title">
              <label for="title">Title</label>
              <input type="text" class="form-control" id="title">
            </div>
            <div class="title_errors field_error"></div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-sm-4">
                <div class="new-event-start_date">
                  <label for="startDate">Start date</label>
                  <input type="text" class="form-control" id="startDate">
                  <div class="start_date_errors field_error"></div>
                </div>
              </div>
              <div class="col-sm-4 col-sm-offset-2">
                <div class="new-event-start_date">
                  <label for="startTime">Start time</label>
                  <input type="text" class="form-control" id="startTime">
                </div>
              </div>
            </div>
          </div>

          <div class="form-group">
            <div class="row">
              <div class="col-sm-4">
                <div class="new-event-end_date">
                  <label for="endDate">End date</label>
                  <input type="text" class="form-control" id="endDate">
                  <div class="start_date_errors field_error"></div>
                </div>
              </div>
                
              <div class="col-sm-4 col-sm-offset-2">
                <div class="new-event-end_time">
                  <label for="endTime">End time</label>
                  <input type="text" class="form-control" id="endTime">
                </div>
              </div>
            </div>
          </div>

          <div class="periodic-checkbox-wrapper">
            <div class="checkbox offset-checkbox">
              <label>
                <input type="checkbox" value="true" id="markedAsPeriodic">
                <span class="periodic-input-label"> Periodic?</span>
              </label>
            </div>
          </div>

          <div class="form-group hide in end-series-date-area">
            <div class="row">
              <div class="col-sm-4">
                <div class="new-event-end_date">
                  <label for="endDateOfSeries">End date of series</label>
                  <input type="text" class="form-control" id="endDateOfSeries">
                </div>
              </div>
              <div class="col-sm-6">
                <div class="new-event-repeat_interval">
                  <%= label_tag 'repeatInterval', 'Repeat interval' %>
                  <%= select_tag 'repeatInterval', options_for_select(Event.repeat_intervals.to_a), prompt: 'Выберите интервал', class: "form-control" %>
                </div>
                <div class="repeat_interval_errors"></div>
              </div>
            </div>
          </div>
          <div class="form-group hide in bulk-update-area">
            <div class="radio offset-radio">
              <label>           
                <input name="updateOptions" id="updateOnlyThis" type="radio" value="onlyThis" />
                <span class="input-label">Update only this instance</span>
              </label>
            </div>
            <div class="radio offset-radio">
              <label>
                <input name="updateOptions" id="updateAll" value="all" type="radio" checked>
                <span class="input-label">Update all for this series</span>
              </label>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button id="deleteEventBtn" class="pull-left btn btn-danger hide">Delete</button>
          <input class="btn btn-success" id="saveEvent" type="submit" value="Save">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div id="popupDeleteOneBasedModal" class="delete-event modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h3>Event's deleting</h3>
      </div>
      <div class="modal-body">
        <form class="event-form">
          <div class="radio offset-radio">
            <label>
              <input name="deleteOptions" id="deleteOnlyThis" type="radio" value="onlyThis">
              <span class="input-label">Delete only this instance</span>
            </label>
          </div>
          <div class="second-option">
            <div class="radio offset-radio">
              <label>
                <input name="deleteOptions" id="deleteAll" value="all" type="radio" checked>
                <span class="input-label">Delete all events from this series</span>
              </label>
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button id="deleteApplyBtn" type="button" class="btn btn-danger">Apply</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Is repeated:</strong>
  <%= @event.repeat_interval %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>